// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Locadora.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Locadora.Infra.Models;

public partial class AgenciaContext : DbContext
{
    public AgenciaContext()
    {
    }

    public AgenciaContext(DbContextOptions<AgenciaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Car> Cars { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Register> Registers { get; set; }
}